const Status = Object.freeze({
    COMPILATION_ERROR: "COMPILATION_ERROR",
    RUNTIME_ERROR: "RUNTIME_ERROR",
    MEMORY_LIMIT_EXCEEDED: "MEMORY_LIMIT_EXCEEDED",
    TIME_LIMIT_EXCEEDED: "TIME_LIMIT_EXCEEDED",
    SUCCESS: "SUCCESS"
})

module.exports = Status